#!/bin/bash

set -e;

if [ $# -ge 1 ]; then
    shsh="$1";
else
    shsh=();
    while read -r; do
        if ! [ -z "$REPLY" ]; then
            shsh+=("$REPLY");
        fi;
    done <<<"$(find . -type f -name '*.shsh')";
    while read -r; do
        if ! [ -z "$REPLY" ]; then
            shsh+=("$REPLY");
        fi;
    done <<<"$(find . -type f -name '*.shsh2')";
    if [ "${#shsh[@]}" -gt 1 ]; then
        echo 'More than one shsh/shsh2 file found in current directory. Please specify one.';
        exit 1;
    elif [ "${#shsh[@]}" -lt 1 ]; then
        echo 'No shsh/shsh2 file found in current directory. Please specify one.';
        exit 1;
    fi;
    shsh="${shsh[0]}";
fi;

if [ $# -ge 2 ]; then
    apticket="$2";
else
    apticket='apticket.der';
fi;

if plutil -extract ApImg4Ticket xml1 -o - "$shsh" &>/dev/null; then # Img4 format
    plutil -extract ApImg4Ticket xml1 -o - "$shsh" | xmllint -xpath '/plist/data/text()' - | base64 -D >"$apticket";
else # Img3 format
    plutil -extract APTicket xml1 -o - "$shsh" | xmllint -xpath '/plist/data/text()' - | base64 -D >"$apticket";
fi;
